name: "CI/CD Workflow"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_DEPLOY_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ubuntu@${{ secrets.EC2_HOST }} "
          if [ ! -d "/home/ubuntu/Laravel-scheduler-hackernews-api" ]; then
            git clone git@github.com:juzoace/Laravel-scheduler-hackernews-api.git /home/ubuntu/Laravel-scheduler-hackernews-api
          fi
          cd /home/ubuntu/Laravel-scheduler-hackernews-api
          git pull origin master
          echo '
          APP_NAME=Laravel
          APP_ENV=production
          APP_KEY=
          APP_DEBUG=false
          APP_URL=http://localhost
          LOG_CHANNEL=stack
          LOG_LEVEL=debug
          DB_CONNECTION=mysql
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=3306
          DB_DATABASE=hackernews-db
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          ...
          # Continue with other environment variables
          REDIS_HOST=127.0.0.1
          REDIS_PASSWORD=null
          REDIS_PORT=6379
          REDIS_CLIENT=predis
          ' > .env
          composer install --no-dev
          php artisan migrate
          "
