name: "CI/CD Workflow"

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.1]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer install
          php -r "copy('.env.example', '.env');"
          php artisan key:generate
          php artisan passport:keys

      - name: Execute tests
        run: vendor/bin/phpunit

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_DEPLOY_KEY }}" > my_key.pem
          chmod 600 my_key.pem
          ssh -o StrictHostKeyChecking=no -i my_key.pem ubuntu@${{ secrets.EC2_HOST }} "
          if [ ! -d "/home/ubuntu/Laravel-scheduler-hackernews-api" ]; then
            git clone git@github.com:juzoace/Laravel-scheduler-hackernews-api.git /home/ubuntu/Laravel-scheduler-hackernews-api
          fi
          cd /home/ubuntu/Laravel-scheduler-hackernews-api
          git pull origin master
          echo '
          APP_NAME=Laravel
          APP_ENV=local
          APP_KEY=
          APP_DEBUG=true
          APP_URL=http://localhost
          LOG_CHANNEL=stack
          LOG_LEVEL=debug
          DB_CONNECTION=mysql
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=3306
          DB_DATABASE=hackernews-db
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          MEMCACHED_HOST=127.0.0.1
          MAIL_MAILER=smtp
          MAIL_HOST=mailhog
          MAIL_PORT=1025
          MAIL_USERNAME=null
          MAIL_PASSWORD=null
          MAIL_ENCRYPTION=null
          MAIL_FROM_ADDRESS=null
          MAIL_FROM_NAME="${APP_NAME}"
          AWS_ACCESS_KEY_ID=
          AWS_SECRET_ACCESS_KEY=
          AWS_DEFAULT_REGION=us-east-1
          AWS_BUCKET=
          PUSHER_APP_ID=
          PUSHER_APP_KEY=
          PUSHER_APP_SECRET=
          PUSHER_APP_CLUSTER=mt1
          MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
          MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
          BROADCAST_DRIVER=log
          CACHE_DRIVER=redis
          QUEUE_CONNECTION=redis
          SESSION_DRIVER=redis
          SESSION_LIFETIME=120
          REDIS_HOST=127.0.0.1
          REDIS_PASSWORD=null
          REDIS_PORT=6379
          REDIS_CLIENT=predis
          ' > .env
          composer install --no-dev
          php artisan migrate
          "
